import {escapeHtml as esc,moveSlide,duplicateSlide,isEditor} from './ui.js';
const $=selector=>document.querySelector(selector);
const invoke=(name,args={})=>{if(!window.__TAURI__)return Promise.reject(new Error('Open this editor in the native Tauri application.'));return window.__TAURI__.core.invoke(name,args);};
let themes=[],theme=null,review=null,projectId='',slideIndex=0,view='brief',markdown=true,zoom=0,grid=false,requestVersion=0,saveTimer,toastTimer,contextIndex=0;
let saveQueue=Promise.resolve();
const newId=()=>`project-${Date.now()}-${crypto.randomUUID().slice(0,8)}`;
function toast(message){$('#toast').textContent=String(message);$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function safe(action){return async(...args)=>{try{await action(...args);}catch(error){toast(error.message??error);$('#status-detail').textContent='Check the input and try again';}};}
function showView(name){view=name;document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#main').scrollTop=0;if(name==='slides')renderSlides();if(name==='home')safe(renderRecent)();}
function setFormat(md){markdown=md;$('#format-md').classList.toggle('active',md);$('#format-json').classList.toggle('active',!md);$('.editor-panel .panel-header span').textContent=md?'brief.md':'brief.json';}
function scheduleSave(){clearTimeout(saveTimer);$('#save-status').textContent='Unsaved changes';saveTimer=setTimeout(()=>safe(save)(),700);}
async function save(){if(!review||!projectId)return;const project={project_version:1,id:projectId,brief:$('#brief-input').value,story:structuredClone(review.story),theme:structuredClone(theme),updated_ms:Date.now()};saveQueue=saveQueue.catch(()=>{}).then(()=>invoke('save_project',{project}));await saveQueue;if(project.id===projectId)$('#save-status').textContent='Saved locally';}
function accept(next){review=next;theme=next.theme;slideIndex=Math.min(slideIndex,next.story.presentation.slides.length-1);$('#project-title').textContent=next.story.presentation.title;$('#finding-count').textContent=next.diagnostics.findings.length;$('#slide-count').textContent=`${next.previews.length} slides`;$('#preview-theme').textContent=theme.name.toUpperCase();$('#brief-preview').innerHTML=next.previews[0]??'';$('#status-detail').textContent=`${next.previews.length} slides · ${next.diagnostics.findings.length} findings · ${theme.name}`;renderStory();renderDoctor();renderEvidence();renderThemes();if(view==='slides')renderSlides();scheduleSave();}
async function compile(){const request=++requestVersion;const input=$('#brief-input').value;$('#compile-button').disabled=true;$('#status-detail').textContent='Compiling locally…';try{const next=await invoke('compile_brief',{input,markdown,theme});if(request===requestVersion)accept(next);}finally{if(request===requestVersion)$('#compile-button').disabled=false;}}
async function refresh(story=review?.story){if(!story)return;const request=++requestVersion;const next=await invoke('review_story',{story,theme});if(request===requestVersion)accept(next);}
function renderStory(){if(!review)return;$('#story-map').innerHTML=review.story.presentation.slides.map((s,i)=>`<article class="story-card" data-index="${i}"><div class="story-card-preview" data-edit="${i}">${review.previews[i]}</div><div class="story-card-info"><span class="role-label">${String(i+1).padStart(2,'0')} / ${esc(s.role)}</span><h3>${esc(s.title)}</h3><p>${esc(s.purpose)}</p><div class="story-card-actions"><button data-edit="${i}">Edit</button><button data-move="${i}" data-direction="-1" aria-label="Move slide ${i+1} earlier">←</button><button data-move="${i}" data-direction="1" aria-label="Move slide ${i+1} later">→</button></div></div></article>`).join('');}
function renderSlides(){if(!review)return;$('#thumbnails').innerHTML=review.previews.map((svg,i)=>`<button class="thumbnail ${i===slideIndex?'active':''}" data-slide="${i}" aria-label="Slide ${i+1}: ${esc(review.story.presentation.slides[i].title)}">${svg}<span>${String(i+1).padStart(2,'0')}</span></button>`).join('');$('#active-slide-label').textContent=`${slideIndex+1} / ${review.previews.length}`;$('#slide-canvas').classList.toggle('grid-canvas',grid);$('#slide-canvas').innerHTML=grid?review.previews.map((svg,i)=>`<button data-slide="${i}" aria-label="Open slide ${i+1}">${svg}</button>`).join(''):review.previews[slideIndex];const svg=$('#slide-canvas svg');if(svg&&!grid)svg.style.width=zoom?`${zoom}%`:'100%';$('#zoom-label').textContent=zoom?`${zoom}%`:'Fit slide';const s=review.story.presentation.slides[slideIndex];$('#slide-title').value=s.title;$('#slide-purpose').value=s.purpose;$('#slide-role').value=s.role;$('#slide-layout').value=s.layout;$('#slide-content').value=JSON.stringify(s.blocks,null,2);$('#slide-notes').value=s.notes;}
function renderDoctor(){if(!review)return;const r=review.diagnostics;$('#doctor-summary').innerHTML=[['Findings',r.findings.length],['Claims linked',`${r.linked_claims} / ${r.claims}`],['Author-confirmed',r.author_confirmed_claims]].map(([label,value])=>`<div class="stat"><strong>${value}</strong><span>${label}</span></div>`).join('');$('#diagnostics').innerHTML=r.findings.length?r.findings.map(f=>`<article class="finding"><span class="severity ${esc(f.severity)}">${esc(f.severity)}</span><div><h3>${esc(f.message)}</h3><p>${esc(f.action)}</p><small class="role-label">${esc(f.code)}</small></div>${f.slide?`<button data-diagnostic-slide="${esc(f.slide)}">View slide ↗</button>`:''}</article>`).join(''):'<div class="empty-state">No structural findings for this story. Source accuracy and viewer fidelity still need author review.</div>';}
function renderEvidence(){if(!review)return;const slides=review.story.presentation.slides;const content=slides.filter(s=>s.claims.length||s.evidence.length).map(s=>`<article class="settings-card"><h2>${esc(s.title)}</h2>${s.claims.map(c=>`<p><strong>${esc(c.id)}</strong> ${esc(c.text)} ${c.assumption?'(assumption)':''}</p>`).join('')}${s.evidence.map(e=>`<p><strong>${esc(e.citation.label)}</strong><br>${esc(e.reference)}<br>${esc(e.excerpt)}<br><small>Owner: ${esc(e.owner||'not recorded')} · ${e.author_confirmed?'author-confirmed':'unreviewed'} · linked to ${esc(e.claim_ids.join(', ')||'no claims')}</small></p>`).join('')}</article>`).join('');$('#evidence-list').innerHTML=content||'<div class="empty-state"><h2>No claim records yet.</h2><p>Add typed claims and evidence to the native story JSON. The compiler does not invent sources or assert that your content is true.</p><button id="evidence-json">Inspect the story JSON</button></div>';}
function renderThemes(){if(!theme)return;$('#theme-grid').innerHTML=themes.map(t=>`<button class="theme-card ${t.name===theme.name?'active':''}" data-theme="${esc(t.name)}"><div class="theme-swatch" style="background:#${t.background};color:#${t.foreground}"><small style="color:#${t.accent}">A VISUAL ARGUMENT</small>Clear ideas.<br>Lasting decisions.</div><div class="theme-caption"><span>${esc(t.name[0].toUpperCase()+t.name.slice(1))}</span><span>${t.title_size}pt</span></div></button>`).join('');$('#brand-json').value=JSON.stringify(theme,null,2);}
async function renderRecent(){const recent=await invoke('recent_projects');$('#recent-projects').innerHTML=recent.length?recent.map(p=>`<button class="recent-card" data-project="${esc(p.id)}"><span class="eyebrow">${esc(p.theme)} / ${p.slides} SLIDES</span><h3>${esc(p.title)}</h3><p>Saved ${new Date(p.updated_ms).toLocaleString()}</p></button>`).join(''):'<div class="empty-state">Your presentations will appear here. They are stored as local project files.</div>';}
async function newProject(){await save();requestVersion++;projectId=newId();slideIndex=0;setFormat(true);$('#brief-input').value=await invoke('example_brief');theme=themes.find(t=>t.name==='midnight');sourceChanged();await compile();showView('brief');}
function sourceChanged(){$('#source-length').textContent=`${$('#brief-input').value.length.toLocaleString()} characters`;scheduleSave();}
async function openFile(){const result=await invoke('open_input');if(!result)return;await save();projectId=newId();$('#brief-input').value=result[0];setFormat(result[1]);sourceChanged();await compile();showView('brief');}
async function exportDeck(){if(!review)return;$('#export-button').disabled=true;try{await save();const result=await invoke('export_deck',{story:review.story,theme});if(result){$('#export-path').textContent=result.split(/[\\/]/).pop();$('#export-path').title=result;$('#export-result').showModal();}}finally{$('#export-button').disabled=false;}}
const commands=[['Compile story',()=>compile()],['Open input file',()=>openFile()],['New presentation',()=>newProject()],['Export PowerPoint',()=>exportDeck()],['Brief editor',()=>showView('brief')],['Story map',()=>showView('story')],['Slide editor',()=>showView('slides')],['Narrative Doctor',()=>showView('doctor')],['Evidence',()=>showView('evidence')],['Themes and brand',()=>showView('themes')],['Draft assistant',()=>showView('provider')],['Recent presentations',()=>showView('home')],['Appearance and shortcuts',()=>showView('settings')]];
function renderCommands(){const query=$('#command-search').value.toLowerCase();$('#command-list').innerHTML=commands.map(([name],i)=>[name,i]).filter(([name])=>name.toLowerCase().includes(query)).map(([name,i])=>`<button type="button" data-command="${i}">${esc(name)}</button>`).join('');}
function palette(){$('#command-search').value='';renderCommands();$('#palette').showModal();$('#command-search').focus();}
$('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view);};
$('#home-button').onclick=()=>showView('home');$('#new-project').onclick=safe(newProject);$('#home-new').onclick=safe(newProject);$('#open-input').onclick=safe(openFile);$('#settings-button').onclick=()=>showView('settings');$('#compile-button').onclick=safe(compile);$('#sample-button').onclick=safe(async()=>{$('#brief-input').value=await invoke('example_brief');setFormat(true);sourceChanged();await compile();});$('#brief-input').oninput=sourceChanged;$('#format-md').onclick=()=>setFormat(true);$('#format-json').onclick=()=>setFormat(false);$('#preview-button').onclick=()=>showView('slides');$('#export-button').onclick=safe(exportDeck);$('#export-close').onclick=()=>$('#export-result').close();$('#palette-button').onclick=palette;$('#command-search').oninput=renderCommands;
$('#palette form').onsubmit=e=>{e.preventDefault();$('#command-list button')?.click();};
$('#palette').onkeydown=e=>{if(!['ArrowDown','ArrowUp'].includes(e.key))return;e.preventDefault();const buttons=[...$('#command-list').querySelectorAll('button')];if(!buttons.length)return;const current=buttons.indexOf(document.activeElement);buttons[(current+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length].focus();};
$('#command-list').onclick=safe(async e=>{const b=e.target.closest('[data-command]');if(b){$('#palette').close();await commands[Number(b.dataset.command)][1]();}});
$('#story-map').onclick=safe(async e=>{const edit=e.target.closest('[data-edit]');if(edit){slideIndex=Number(edit.dataset.edit);showView('slides');return;}const move=e.target.closest('[data-move]');if(move){const story=structuredClone(review.story);if(moveSlide(story,Number(move.dataset.move),Number(move.dataset.direction)))await refresh(story);}});
$('#story-add').onclick=safe(async()=>{const story=structuredClone(review.story);story.presentation.slides.push({id:`slide-${crypto.randomUUID()}`,title:'State the next point',purpose:'Explain how this advances the story',role:'context',layout:'stack',blocks:[{type:'text',text:{paragraphs:[{runs:[{text:'Add your author-owned content.',bold:false,italic:false,hyperlink:null}],bullet:false}]}}],claims:[],evidence:[],notes:'',transition:''});await refresh(story);slideIndex=story.presentation.slides.length-1;showView('slides');});
for(const selector of ['#thumbnails','#slide-canvas'])$(selector).onclick=e=>{const b=e.target.closest('[data-slide]');if(b){slideIndex=Number(b.dataset.slide);grid=false;renderSlides();}};
$('#slide-previous').onclick=()=>{slideIndex=Math.max(0,slideIndex-1);renderSlides();};$('#slide-next').onclick=()=>{slideIndex=Math.min(review.previews.length-1,slideIndex+1);renderSlides();};$('#zoom-in').onclick=()=>{zoom=Math.min(250,(zoom||100)+25);renderSlides();};$('#zoom-out').onclick=()=>{zoom=Math.max(25,(zoom||100)-25);renderSlides();};$('#fit-slide').onclick=()=>{zoom=0;renderSlides();};$('#fit-width').onclick=()=>{zoom=100;renderSlides();};$('#fullscreen').onclick=safe(async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await $('#slide-canvas').requestFullscreen();});$('#grid-toggle').onclick=()=>{grid=!grid;renderSlides();};
$('#slide-form').onsubmit=safe(async e=>{e.preventDefault();const story=structuredClone(review.story),s=story.presentation.slides[slideIndex];s.title=$('#slide-title').value;s.purpose=$('#slide-purpose').value;s.role=$('#slide-role').value;s.layout=$('#slide-layout').value;s.blocks=JSON.parse($('#slide-content').value);s.notes=$('#slide-notes').value;await refresh(story);});
$('#diagnostics').onclick=e=>{const b=e.target.closest('[data-diagnostic-slide]');if(b){slideIndex=review.story.presentation.slides.findIndex(s=>s.id===b.dataset.diagnosticSlide);showView('slides');}};
$('#theme-grid').onclick=safe(async e=>{const b=e.target.closest('[data-theme]');if(b){theme=themes.find(t=>t.name===b.dataset.theme);await refresh();}});
$('#brand-import').onclick=safe(async()=>{const next=await invoke('import_brand',{story:review.story});if(next)accept(next);});
$('#brand-toggle').onclick=()=>$('#brand-form').hidden=!$('#brand-form').hidden;$('#brand-form').onsubmit=safe(async e=>{e.preventDefault();const next=JSON.parse($('#brand-json').value);const previous=theme;theme=next;try{await refresh();}catch(error){theme=previous;throw error;}});
$('#evidence-list').onclick=e=>{if(e.target.closest('#evidence-json')){$('#brief-input').value=JSON.stringify(review.story,null,2);setFormat(false);sourceChanged();showView('brief');}};
$('#appearance-toggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('appearance',document.body.classList.contains('light')?'light':'dark');};
$('#recent-projects').onclick=safe(async e=>{const b=e.target.closest('[data-project]');if(!b)return;await save();const project=await invoke('load_project',{id:b.dataset.project});projectId=project.id;theme=project.theme;$('#brief-input').value=project.brief;setFormat(project.brief.trim().startsWith('#'));sourceChanged();await refresh(project.story);showView('story');});
$('#story-map').oncontextmenu=e=>{const card=e.target.closest('[data-index]');if(!card)return;e.preventDefault();contextIndex=Number(card.dataset.index);$('#context-menu').hidden=false;$('#context-menu').style.left=`${Math.min(e.clientX,window.innerWidth-190)}px`;$('#context-menu').style.top=`${Math.min(e.clientY,window.innerHeight-140)}px`;$('#context-edit').focus();};
$('#context-edit').onclick=()=>{slideIndex=contextIndex;showView('slides');$('#context-menu').hidden=true;};$('#context-duplicate').onclick=safe(async()=>{const story=structuredClone(review.story);duplicateSlide(story,contextIndex,`slide-${crypto.randomUUID()}`);$('#context-menu').hidden=true;await refresh(story);});$('#context-remove').onclick=safe(async()=>{if(review.story.presentation.slides.length===1){toast('Keep at least one slide in the story.');return;}const story=structuredClone(review.story);story.presentation.slides.splice(contextIndex,1);$('#context-menu').hidden=true;await refresh(story);});
document.addEventListener('click',e=>{if(!e.target.closest('#context-menu'))$('#context-menu').hidden=true;});document.addEventListener('keydown',safe(async e=>{if(e.key==='Escape'){$('#context-menu').hidden=true;return;}if((e.metaKey||e.ctrlKey)&&['k','n','o','e','Enter'].includes(e.key)){e.preventDefault();if(e.key==='k')palette();if(e.key==='n')await newProject();if(e.key==='o')await openFile();if(e.key==='e')await exportDeck();if(e.key==='Enter')await compile();}else if(view==='slides'&&!document.querySelector('dialog[open]')&&!isEditor(e.target)){if(e.key==='ArrowLeft')$('#slide-previous').click();if(e.key==='ArrowRight')$('#slide-next').click();}}));

$('#provider-copy').onclick=()=>{$('#provider-input').value=$('#brief-input').value;$('#provider-approval').checked=false;};
for(const selector of ['#provider-input','#provider-endpoint','#provider-model','#provider-kind'])$(selector).addEventListener('input',()=>$('#provider-approval').checked=false);
$('#provider-form').onsubmit=safe(async e=>{e.preventDefault();const config={provider:$('#provider-kind').value,endpoint:$('#provider-endpoint').value,model:$('#provider-model').value};$('#provider-send').disabled=true;try{$('#provider-output').value=await invoke('draft_brief',{config,input:$('#provider-input').value,apiKey:$('#provider-key').value||null,approved:$('#provider-approval').checked});$('#provider-apply').disabled=false;toast('Draft received. Review the copy and any claims before applying it.');}finally{$('#provider-send').disabled=false;$('#provider-approval').checked=false;}});
$('#provider-apply').onclick=()=>{$('#brief-input').value=$('#provider-output').value;setFormat(true);sourceChanged();showView('brief');toast('Draft added to the editor. Review it, then compile.');};
async function start(){if(window.__TAURI__?.event)await window.__TAURI__.event.listen('storyboard-close-requested',safe(async()=>{clearTimeout(saveTimer);await save();await invoke('finish_close');}));document.body.classList.toggle('light',localStorage.getItem('appearance')==='light');themes=await invoke('theme_catalog');theme=themes.find(t=>t.name==='midnight');projectId=newId();$('#brief-input').value=await invoke('example_brief');sourceChanged();await compile();if(window.__TAURI__?.webviewWindow){await window.__TAURI__.webviewWindow.getCurrentWebviewWindow().onDragDropEvent(safe(async e=>{if(e.payload.type==='drop'&&e.payload.paths.length){const [text,md]=await invoke('import_drop',{path:e.payload.paths[0]});await save();projectId=newId();$('#brief-input').value=text;setFormat(md);sourceChanged();await compile();showView('brief');}}));}}
safe(start)();
