// Every downloadable deck is produced by the native CLI. All scenarios/data are synthetic.
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
const root=fileURLToPath(new URL('../../',import.meta.url));
const binary=join(root,'target/release/storyboard');
const scenarios=[
['startup-pitch','Fieldwork — the research workspace','Seed investment committee','research handoffs','Documents lose the connection between excerpts and decisions.','Improve document templates','Build a focused research workspace','Pilot one handoff workflow before expanding integrations.','Research lead','midnight'],
['product-roadmap','A roadmap with room to learn','Product leadership','release planning','Too many parallel initiatives obscure the next customer problem.','Fund every initiative','Sequence one outcome per release','Reserve a release for reliability before adding new workflows.','Product manager','product'],
['ai-strategy','Where AI earns a place in the workflow','Technology steering group','AI adoption','The team has prototypes but no agreed evaluation boundary.','Roll out a broad assistant','Pilot one bounded drafting task','Pilot drafting with explicit author review and a measured stop condition.','AI program lead','technical'],
['engineering-architecture','Make the runtime boundary explicit','Platform engineering','service architecture','Synchronous dependencies make failures spread across teams.','Add retries everywhere','Isolate the critical request path','Keep the read path small and move optional work behind durable queues.','Platform lead','technical'],
['quarterly-business-review','A quarter of focus, not a list of activities','Executive team','quarterly planning','Activity reports bury the outcomes that need a decision.','Increase the initiative count','Concentrate on one retention workflow','Fund one retention experiment and stop two low-evidence initiatives.','Operations lead','consulting'],
['consulting-recommendation','Choose the operating model the team can sustain','Client steering committee','operating model','A centralized queue slows decisions that need local context.','Centralize every request','Delegate within explicit guardrails','Delegate routine decisions with a weekly exception review.','Engagement owner','consulting'],
['market-analysis','Find the reachable first market','Go-to-market leads','market selection','Broad market estimates do not reveal an accessible first customer.','Target every segment','Start with one observable workflow','Test one segment where the buyer and workflow owner are the same person.','Market research lead','research'],
['launch-plan','A launch that earns the next release','Launch working group','product launch','Distribution is scheduled before onboarding and support are ready.','Launch broadly now','Release to a bounded pilot cohort','Open the pilot after onboarding and escalation paths are exercised.','Launch owner','modern'],
['incident-postmortem','Turn a recovery into a reliability decision','Service owners','incident recovery','The service recovered but the same dependency remains on the critical path.','Patch the immediate trigger','Remove the shared failure boundary','Prioritize isolation and test the recovery procedure before closing the incident.','Reliability lead','terminal'],
['design-review','Make the next step visible','Design and product team','workflow design','Readers see many controls without knowing which action advances the task.','Expose every control at once','Guide the primary path','Keep advanced controls available while making the next action explicit.','Design lead','swiss'],
['research-report','What the pilot can and cannot tell us','Research stakeholders','research synthesis','Observed notes and hypotheses are mixed in the same summary.','Present every observation as a result','Separate observations and hypotheses','Publish bounded findings with source excerpts and unresolved questions.','Research owner','research'],
['investment-memo','Evaluate the pilot before funding scale','Internal investment committee','capital allocation','The proposal assumes adoption without an observed workflow.','Fund full expansion','Fund a narrow validation stage','Release funding in stages tied to observed workflow evidence.','Investment sponsor','investor'],
['sales-proposal','A proposal built around one customer outcome','Buyer and delivery team','solution delivery','The proposal lists features without explaining the delivery trade-off.','Sell the full platform','Scope one outcome first','Start with a fixed-scope implementation and a shared review checkpoint.','Account owner','editorial'],
['technical-rfc','A migration boundary the team can test','Engineering reviewers','data migration','Replacing the storage layer and API simultaneously makes rollback unclear.','Replace everything together','Migrate one boundary at a time','Keep a tested read boundary while migrating writes behind an explicit switch.','RFC author','mono'],
['project-kickoff','Start with an owned decision','Cross-functional delivery team','project kickoff','The kickoff describes ambition without an owner or stop condition.','Run all workstreams immediately','Define the first measurable milestone','Assign a single milestone owner and inspect evidence before expanding scope.','Delivery lead','minimal'],
['executive-briefing','The decision behind the update','Executive sponsor','executive decisions','Status is clear but the requested decision is absent.','Continue the current plan','Change the sequence','Approve the sequence change and review the affected dependencies.','Executive sponsor','midnight'],
['company-strategy','Choose where the company will say no','Leadership team','strategy planning','Every growth idea is treated as a priority and capacity is not visible.','Pursue all adjacent markets','Defend one core workflow','Choose one core workflow and publish the work that will stop.','Strategy owner','investor'],
['competitive-analysis','Compare mechanisms, not marketing claims','Product strategy group','competitive evaluation','Feature lists conceal differences in deployment and data ownership.','Match every competitor feature','Differentiate on the operating boundary','Test local deployment and reviewability as the first differentiators.','Strategy analyst','consulting'],
['security-review','Reduce the paths that can expose a project','Security and platform leads','security controls','An optional integration can access more project content than it needs.','Grant broad project access','Bound each transfer explicitly','Permit only the selected text fields and keep credentials out of exports.','Security owner','technical'],
['open-source-overview','Storyboard Studio — an inspectable presentation compiler','Developers and maintainers','native presentation tooling','A polished slide does not explain where its claims or layout came from.','Generate opaque slide images','Compile editable objects from a typed story','Build a Rust core shared by the CLI and desktop, with visible diagnostics.','Maintainer','swiss'],
];
const text=value=>({type:'text',text:{paragraphs:[{runs:[{text:value,bold:false,italic:false,hyperlink:null}],bullet:false}]}});
const card=(title,body)=>({type:'card',title,body});
const links=[];
for(const [index,s] of scenarios.entries()){
 const [id,title,audience,topic,problem,a,b,recommendation,owner,theme]=s;
 const dir=join(root,'gallery/native',id);await mkdir(dir,{recursive:true});
 const input=`# ${title}\nAudience: ${audience}\nObjective: Approve a bounded next step for ${topic}\nOwner: ${owner}\nNext action: Approve the pilot and inspect the review evidence\nTheme: ${theme}\nSynthetic: true\n\n## The context for ${topic}\nThis fictional team needs a decision it can explain, execute, and revisit. ${problem}\nNotes: Synthetic scenario. Figures, roles and organizations are invented to demonstrate the renderer.\n\n## The problem is the missing decision boundary\n${problem}\n\n## Evidence to gather before committing\nObserve the current workflow, record its limitations, and review source excerpts with the accountable owner.\n\n## Two paths make the trade-off explicit\n### ${a}\nFaster to start, with the current operating limitations.\n### ${b}\nMore focused initial work, with a clearer review boundary.\n\n## Recommend the bounded path\n${recommendation}\n\n## Risks to review before expansion\nKeep the scope narrow. Check whether the new workflow adds manual effort or moves risk elsewhere. Record the unresolved question instead of treating an assumption as a finding.\n\n## Next action: approve the pilot and own the review\n### Owner\n${owner} owns the first milestone and its evidence.\n### Review\nInspect the pilot evidence before approving the next stage.\n`;
 await writeFile(join(dir,'brief.md'),input);
 const compiled=JSON.parse(execFileSync(binary,['compile',join(dir,'brief.md')],{encoding:'utf8'}));
 const evidenceSlide=compiled.presentation.slides[2];
 const categories=['Baseline','Pilot','Review'];const values=[12+(index%4)*3,18+(index%5)*3,24+(index%6)*2];
 if(index%3===0)evidenceSlide.blocks=[{type:'chart',chart:{title:'Illustrative pilot checkpoints',categories,series:[{name:'Synthetic score',values}],kind:index%2?'line':'bar',source_note:'Invented values for layout demonstration; not observed results.'}}];
 else if(index%3===1)evidenceSlide.blocks=[{type:'table',table:{columns:['Checkpoint','Owner','Evidence to inspect'],rows:[['Baseline',owner,'Current workflow notes'],['Pilot',owner,'Observed handoff or task'],['Review','Decision sponsor','Bounded continuation decision']],summary:'Synthetic review checkpoints and source responsibilities.'}}];
 else evidenceSlide.blocks=[{type:'metric',value:'1',label:'Bounded workflow first',context:'An authored scope constraint for this fictional scenario, not a measured product result.'}];
 evidenceSlide.claims=[{id:'scope',text:'The example uses synthetic content and illustrative review checkpoints.',assumption:true}];
 evidenceSlide.evidence=[{id:'synthetic-source',citation:{label:'Synthetic gallery input',locator:'brief.md',author:'Storyboard Studio'},kind:'note',reference:'Authored fixture',excerpt:'No real customer, market or investment results are claimed.',owner,claim_ids:['scope'],author_confirmed:false,checked_date:null}];
 for(let i=1;i<compiled.presentation.slides.length;i++)compiled.presentation.slides[i].transition=`The preceding slide establishes why this ${compiled.presentation.slides[i].role} matters for the decision.`;
 if(index%4===0)compiled.presentation.slides.splice(5,0,{id:`quote-${index}`,title:'Keep the reasoning inspectable',purpose:'State the operating principle',role:'implications',layout:'stack',blocks:[{type:'quote',text:'A decision should keep its supporting evidence and unresolved assumptions in view.',attribution:'Authored synthetic principle — not a customer quotation'}],claims:[],evidence:[],notes:'Synthetic authored principle.',transition:'The recommendation needs a reviewable evidence boundary.'});
 if(index%5===0)compiled.presentation.slides.splice(2,0,{id:`mechanism-${index}`,title:'A smaller boundary makes the work reviewable',purpose:'Explain the mechanism',role:'problem',layout:'columns',blocks:[card('Observe','Start with one actual task.'),card('Decide','Name the trade-off and owner.'),card('Review','Inspect the outcome before expanding.')],claims:[],evidence:[],notes:'Synthetic process diagram represented by editable native cards.',transition:'The context calls for a bounded operating mechanism.'});
 const source=join(dir,'input.story.json');await writeFile(source,JSON.stringify(compiled,null,2));
 execFileSync(binary,['render',source,'-o',join(dir,'deck.pptx'),'--force']);
 execFileSync(binary,['verify',join(dir,'deck.receipt.json')]);
 await writeFile(join(dir,'diagnostics.json'),execFileSync(binary,['doctor',join(dir,'deck.story.json'),'--json']));
 for(const slide of [1,3,compiled.presentation.slides.length])execFileSync(binary,['preview',join(dir,'deck.story.json'),'--svg','--slide',String(slide),'-o',join(dir,`slide-${String(slide).padStart(2,'0')}.svg`),'--force']);
 await writeFile(join(dir,'README.md'),`# ${title}\n\nSynthetic demonstration generated with the native Rust compiler. Not real client work.\n\n[Brief](brief.md) · [Authored typed input](input.story.json) · [PPTX](deck.pptx) · [Story](deck.story.json) · [Receipt](deck.receipt.json) · [Diagnostics](diagnostics.json)\n\nTheme: **${theme}** · ${compiled.presentation.slides.length} slides.\n\nReproduce: \`storyboard render gallery/native/${id}/input.story.json -o deck.pptx\`.\n`);
 links.push({id,title,theme,slides:compiled.presentation.slides.length,preview:`${id}/slide-01.svg`,pptx:`${id}/deck.pptx`});console.log(`${id}: generated + verified`);
}
await writeFile(join(root,'gallery/native/catalog.json'),JSON.stringify({synthetic:true,renderer:'openxml-rust-1',examples:links},null,2));
await writeFile(join(root,'gallery/native/README.md'),'# Native presentation gallery\n\nEvery example is synthetic and built by the Rust CLI. Editable objects, typed stories, integrity receipts and diagnostics are included. Historical Python decks outside this directory do not certify these native outputs.\n\n'+links.map(e=>`- [${e.title}](${e.id}/README.md) — ${e.theme}, ${e.slides} slides`).join('\n')+'\n\nRebuild all examples with `node scripts/native/generate-gallery.mjs` after `cargo build --release`. Node is authoring tooling, not a product runtime.\n');
