// Package the locally built platform artifacts. Publishing is a separate gh step.
import {cpSync,mkdirSync,copyFileSync,readdirSync,statSync,readFileSync,writeFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';import {join} from 'node:path';
const version=JSON.parse(readFileSync('apps/desktop/src-tauri/tauri.conf.json','utf8')).version;
const target=process.env.STORYBOARD_TARGET??execFileSync('rustc',['-vV'],{encoding:'utf8'}).match(/host: (.*)/)[1];const dir=`output/releases/v${version}`;mkdirSync(dir,{recursive:true});const staging=`${dir}/storyboard-${version}-${target}`;mkdirSync(staging,{recursive:true});
copyFileSync(`target/release/storyboard${process.platform==='win32'?'.exe':''}`,join(staging,process.platform==='win32'?'storyboard.exe':'storyboard'));copyFileSync('LICENSE',join(staging,'LICENSE'));copyFileSync('docs/INSTALLATION.md',join(staging,'INSTALLATION.md'));cpSync('examples',join(staging,'examples'),{recursive:true});
const archive=`storyboard-${version}-${target}.tar.gz`;execFileSync('tar',['-czf',join(dir,archive),'-C',dir,staging.split('/').pop()]);
const assets=[archive];const bundle='target/release/bundle';for(const folder of ['dmg','msi','nsis','appimage','deb']){try{for(const name of readdirSync(join(bundle,folder)))if(/\.(dmg|msi|exe|AppImage|deb)$/.test(name)){const safe=name.replace(/ /g,'-');copyFileSync(join(bundle,folder,name),join(dir,safe));assets.push(safe);}}catch(error){if(error.code!=='ENOENT')throw error;}}
const manifest={version,target,source_commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),rustc:execFileSync('rustc',['--version'],{encoding:'utf8'}).trim(),assets:assets.map(name=>({name,bytes:statSync(join(dir,name)).size,sha256:createHash('sha256').update(readFileSync(join(dir,name))).digest('hex')}))};
writeFileSync(join(dir,'build-manifest.json'),JSON.stringify(manifest,null,2)+'\n');writeFileSync(join(dir,'SHA256SUMS'),manifest.assets.map(a=>`${a.sha256}  ${a.name}`).join('\n')+'\n');console.log(JSON.stringify(manifest,null,2));
